# Generated by Django 3.2.25 on 2024-07-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WastManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_route', models.CharField(max_length=255)),
                ('labelling', models.CharField(max_length=255)),
                ('storage', models.CharField(max_length=255)),
                ('transportation_company_method', models.CharField(max_length=255)),
                ('disposal_company', models.CharField(max_length=255)),
                ('special_instructions', models.TextField()),
            ],
            options={
                'verbose_name': 'Waste Management (FR.AS.032)',
                'verbose_name_plural': 'Waste Managements (FR.AS.032)',
            },
        ),
    ]
