# Generated by Django 3.2.25 on 2025-03-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourceefficiencyandpollutionprevention', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastmanagement',
            options={'verbose_name': 'FR.AS.032_Waste Management', 'verbose_name_plural': 'FR.AS.032_Waste Managements'},
        ),
    ]
