# Generated by Django 5.0.13 on 2025-03-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourceefficiencyandpollutionprevention', '0002_alter_wastmanagement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastmanagement',
            options={'verbose_name': 'FR.AS.032 Waste Management', 'verbose_name_plural': 'FR.AS.032 Waste Managements'},
        ),
    ]
