# Generated by Django 3.2.25 on 2024-07-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riskmanagement', '0006_alter_legalrequirementcontrol_law_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ToolBoxTalks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEvaluationQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('year', models.PositiveIntegerField()),
                ('training_area', models.CharField(max_length=255)),
                ('training_title', models.CharField(max_length=255)),
                ('training_objective', models.TextField()),
                ('training_type', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=255)),
                ('training_entity', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('number_of_trainees', models.PositiveIntegerField()),
                ('training_recipients', models.TextField()),
                ('training_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('training_status', models.CharField(choices=[('Planned', 'Planned'), ('Completed', 'Completed')], max_length=20)),
                ('observations', models.TextField()),
            ],
            options={
                'verbose_name': 'Training Plan (FR.AS.006)',
                'verbose_name_plural': 'Training Plans (FR.AS.006)',
            },
        ),
        migrations.CreateModel(
            name='TrainingNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_by', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('training', models.CharField(max_length=255)),
                ('training_objective', models.TextField()),
                ('proposal_of_training_entity', models.CharField(max_length=255)),
                ('potential_training_participants', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.department')),
            ],
            options={
                'verbose_name': 'Training Need (FR.AS.005)',
                'verbose_name_plural': 'Training Needs (FR.AS.005)',
            },
        ),
        migrations.CreateModel(
            name='TrainingMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('effectiveness', models.CharField(choices=[('Effective', 'Effective'), ('Not effective', 'Ineffective')], max_length=255)),
                ('approved_by', models.CharField(max_length=100)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizationalcapacityandcompetency.position')),
                ('toolbox_talks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizationalcapacityandcompetency.toolboxtalks')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizationalcapacityandcompetency.training')),
            ],
            options={
                'verbose_name': 'Training Matrix (FR.AS.006)',
                'verbose_name_plural': 'Training Matrix (FR.AS.006)',
            },
        ),
        migrations.CreateModel(
            name='TrainingEffectivnessAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('trainee', models.CharField(max_length=100)),
                ('immediate_supervisor', models.CharField(max_length=100)),
                ('answer', models.CharField(choices=[('Satisfactory', 'Satisfactory'), ('Partially Satisfactory', 'Partially Satisfactory'), ('Unsatisfactory', 'Unsatisfactory')], max_length=50)),
                ('human_resource_evaluation', models.CharField(choices=[('effective', 'Effective'), ('ineffective', 'Ineffective')], max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.department')),
                ('training_evaluation_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizationalcapacityandcompetency.trainingevaluationquestions')),
            ],
            options={
                'verbose_name': 'Training Effectiveness Assessment (FR.AS.007)',
                'verbose_name_plural': 'Training Effectiveness Assessments (FR.AS.007)',
            },
        ),
    ]
