# Generated by Django 4.2.19 on 2025-02-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OHSACTING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('terms_of_office_from', models.CharField(blank=True, max_length=100, null=True)),
                ('terms_of_office_to', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OHS ACTING (FR.AS.038)',
                'verbose_name_plural': 'OHS ACTING (FR.AS.038)',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ToolBoxTalks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEffectivnessAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('trainee', models.CharField(max_length=100)),
                ('immediate_supervisor', models.CharField(max_length=100)),
                ('answer', models.CharField(choices=[('Satisfactory', 'Satisfactory'), ('Partially Satisfactory', 'Partially Satisfactory'), ('Unsatisfactory', 'Unsatisfactory')], max_length=50)),
                ('human_resource_evaluation', models.CharField(choices=[('effective', 'Effective'), ('ineffective', 'Ineffective')], max_length=50)),
            ],
            options={
                'verbose_name': 'Training Effectiveness Assessment (FR.AS.007)',
                'verbose_name_plural': 'Training Effectiveness Assessments (FR.AS.007)',
            },
        ),
        migrations.CreateModel(
            name='TrainingEvaluationQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('effectiveness', models.CharField(choices=[('Effective', 'Effective'), ('Not effective', 'Ineffective')], max_length=255)),
                ('actions_training_not_effective', models.TextField(blank=True, null=True)),
                ('approved_by', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Training Matrix (FR.AS.006)',
                'verbose_name_plural': 'Training Matrix (FR.AS.006)',
            },
        ),
        migrations.CreateModel(
            name='TrainingNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_by', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('training', models.CharField(max_length=255)),
                ('training_objective', models.TextField()),
                ('proposal_of_training_entity', models.CharField(max_length=255)),
                ('potential_training_participants', models.TextField()),
            ],
            options={
                'verbose_name': 'Training Need (FR.AS.005)',
                'verbose_name_plural': 'Training Needs (FR.AS.005)',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('year', models.PositiveIntegerField()),
                ('training_area', models.CharField(max_length=255)),
                ('training_title', models.CharField(max_length=255)),
                ('training_objective', models.TextField()),
                ('training_type', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=255)),
                ('training_entity', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('number_of_trainees', models.PositiveIntegerField()),
                ('training_recipients', models.TextField()),
                ('training_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('training_status', models.CharField(choices=[('Planned', 'Planned'), ('Completed', 'Completed')], max_length=20)),
                ('observations', models.TextField()),
            ],
            options={
                'verbose_name': 'Training Plan (FR.AS.006)',
                'verbose_name_plural': 'Training Plans (FR.AS.006)',
            },
        ),
    ]
