# Generated by Django 3.2.25 on 2024-07-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationalcapacityandcompetency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmatrix',
            name='actions_training_not_effective',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
