# Generated by Django 3.2.25 on 2025-03-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizationalcapacityandcompetency', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ohsacting',
            options={'verbose_name': 'FR.AS.038_OHS ACTING', 'verbose_name_plural': 'FR.AS.038_OHS ACTING'},
        ),
        migrations.AlterModelOptions(
            name='trainingeffectivnessassessment',
            options={'verbose_name': 'FR.AS.007_Training Effectiveness Assessment', 'verbose_name_plural': 'FR.AS.007_Training Effectiveness Assessments'},
        ),
        migrations.AlterModelOptions(
            name='trainingmatrix',
            options={'verbose_name': 'FR.AS.006_Training Matrix', 'verbose_name_plural': 'FR.AS.006_Training Matrix'},
        ),
        migrations.AlterModelOptions(
            name='trainingneeds',
            options={'verbose_name': 'FR.AS.005_Training Need', 'verbose_name_plural': 'FR.AS.005_Training Needs'},
        ),
        migrations.AlterModelOptions(
            name='trainingplan',
            options={'verbose_name': 'FR.AS.006_Training Plan', 'verbose_name_plural': 'FR.AS.006_Training Plans'},
        ),
    ]
