# Generated by Django 3.2.25 on 2024-07-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationalcapacityandcompetency', '0002_trainingmatrix_actions_training_not_effective'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='trainingmatrix',
            name='actions_training_not_effective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OHSACTING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('terms_of_office_from', models.CharField(blank=True, max_length=100, null=True)),
                ('terms_of_office_to', models.CharField(blank=True, max_length=100, null=True)),
                ('acceptance_confirmation', models.ManyToManyField(to='organizationalcapacityandcompetency.AcceptanceConfirmation')),
            ],
        ),
    ]
