# Generated by Django 3.2.25 on 2024-07-30 19:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizationalcapacityandcompetency', '0003_auto_20240730_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ohsacting',
            options={'verbose_name': 'OHS ACTING (FR.AS.038)', 'verbose_name_plural': 'OHS ACTING (FR.AS.038)'},
        ),
        migrations.AddField(
            model_name='ohsacting',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 7, 30, 19, 31, 3, 613478, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
