# Generated by Django 5.0.13 on 2025-03-16 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationalcapacityandcompetency', '0003_auto_20250313_0924'),
        ('riskmanagement', '0004_alter_environandsocialriskandimapactassessement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ohsacting',
            options={'verbose_name': 'FR.AS.038 OHS ACTING', 'verbose_name_plural': 'FR.AS.038 OHS ACTING'},
        ),
        migrations.AlterModelOptions(
            name='trainingeffectivnessassessment',
            options={'verbose_name': 'FR.AS.007 Training Effectiveness Assessment', 'verbose_name_plural': 'FR.AS.007 Training Effectiveness Assessments'},
        ),
        migrations.AlterModelOptions(
            name='trainingneeds',
            options={'verbose_name': 'FR.AS.005 Training Need', 'verbose_name_plural': 'FR.AS.005 Training Needs'},
        ),
        migrations.AddField(
            model_name='trainingeffectivnessassessment',
            name='subproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.subproject'),
        ),
        migrations.AddField(
            model_name='trainingneeds',
            name='subproject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingeffectivnessassessment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.department'),
        ),
        migrations.AlterField(
            model_name='trainingneeds',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.department'),
        ),
    ]
