# Generated by Django 3.2.25 on 2024-06-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extcommungrievancemechanism', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimcomplaincontrol',
            options={'verbose_name': 'Claim And Complain Control', 'verbose_name_plural': 'Claim And Complain Controls'},
        ),
        migrations.AlterModelOptions(
            name='claimnoncompliancecontrol',
            options={'verbose_name': 'Non Compliance Control', 'verbose_name_plural': 'Non Compliance Controls'},
        ),
    ]
