# Generated by Django 4.2.19 on 2025-02-23 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extcommungrievancemechanism', '0001_initial'),
        ('riskmanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photodocumentprovingclosure',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaintandclaimrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_and_claim_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaintandclaimrecord',
            name='photos_and_documents_proving_closure',
            field=models.ManyToManyField(blank=True, to='extcommungrievancemechanism.photodocumentprovingclosure'),
        ),
        migrations.AddField(
            model_name='claimnoncompliancecontrol',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_non_compliance_control', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimnoncompliancecontrol',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.department'),
        ),
        migrations.AddField(
            model_name='claimcomplaincontrol',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_complain_control', to=settings.AUTH_USER_MODEL),
        ),
    ]
