# Generated by Django 3.2.25 on 2024-07-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extcommungrievancemechanism', '0002_auto_20240627_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerGrievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('prefered_contact_method', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('FACE_TO_FACE', 'Face to Face')], max_length=50)),
                ('contact', models.CharField(max_length=100)),
                ('prefered_language', models.CharField(choices=[('PORTUGUESE', 'Portuguese'), ('ENGLISH', 'English'), ('OTHER', 'Other')], max_length=50)),
                ('other_language', models.CharField(blank=True, max_length=100, null=True)),
                ('grievance_details', models.TextField()),
                ('unique_identification_of_company_acknolegement', models.CharField(max_length=100)),
                ('name_of_person_acknowledging_grievance', models.CharField(max_length=100)),
                ('position_of_person_acknowledging_grievance', models.CharField(max_length=100)),
                ('date_of_acknowledgement', models.DateField()),
                ('signature_of_person_acknowledging_grievance', models.CharField(max_length=100)),
                ('follow_up_details', models.TextField()),
                ('closed_out_date', models.DateField()),
                ('signature_of_response_corrective_action_person', models.CharField(max_length=100)),
                ('acknowledge_receipt_of_response', models.CharField(max_length=100)),
                ('name_of_person_acknowledging_response', models.CharField(max_length=100)),
                ('signature_of_person_acknowledging_response', models.CharField(max_length=100)),
                ('date_of_acknowledgement_response', models.DateField()),
            ],
            options={
                'verbose_name': 'Worker Grievance (FR.AS.033)',
                'verbose_name_plural': 'Worker Grievances (FR.AS.033)',
            },
        ),
    ]
