# Generated by Django 3.2.25 on 2025-03-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extcommungrievancemechanism', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimcomplaincontrol',
            options={'verbose_name': 'FR.AS.013_Claim And Complain Control', 'verbose_name_plural': 'FR.AS.013_Claim And Complain Controls'},
        ),
        migrations.AlterModelOptions(
            name='claimnoncompliancecontrol',
            options={'verbose_name': 'FR.AS.013_Non Compliance Control', 'verbose_name_plural': 'FR.AS.013_Non Compliance Controls'},
        ),
        migrations.AlterModelOptions(
            name='complaintandclaimrecord',
            options={'verbose_name': 'FR.AS.026_Complaints and Claims Registration Form', 'verbose_name_plural': 'FR.AS.026_Complaints and Claims Registration Form'},
        ),
        migrations.AlterModelOptions(
            name='workergrievance',
            options={'verbose_name': 'FR.AS.033_Worker Grievance', 'verbose_name_plural': 'FR.AS.033_Worker Grievances'},
        ),
    ]
