# Generated by Django 5.0.13 on 2025-03-16 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extcommungrievancemechanism', '0003_auto_20250313_0924'),
        ('riskmanagement', '0004_alter_environandsocialriskandimapactassessement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimnoncompliancecontrol',
            options={'verbose_name': 'FR.AS.013_Non Compliance Control', 'verbose_name_plural': 'FR.AS.013 Non Compliance Controls'},
        ),
        migrations.AlterModelOptions(
            name='complaintandclaimrecord',
            options={'verbose_name': 'FR.AS.026 Complaints and Claims Registration Form', 'verbose_name_plural': 'FR.AS.026 Complaints and Claims Registration Form'},
        ),
        migrations.AlterModelOptions(
            name='workergrievance',
            options={'verbose_name': 'FR.AS.033 Worker Grievance', 'verbose_name_plural': 'FR.AS.033 Worker Grievances'},
        ),
        migrations.RemoveField(
            model_name='claimcomplaincontrol',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='claimnoncompliancecontrol',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='complaintandclaimrecord',
            name='created_by',
        ),
        migrations.AddField(
            model_name='claimnoncompliancecontrol',
            name='subproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.subproject'),
        ),
        migrations.AlterField(
            model_name='claimnoncompliancecontrol',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.department'),
        ),
    ]
