# Generated by Django 3.2.25 on 2024-07-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extcommungrievancemechanism', '0003_workergrievance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workergrievance',
            old_name='unique_identification_of_company_acknolegement',
            new_name='unique_identification_of_company_acknowlegement',
        ),
    ]
