# Generated by Django 3.2.25 on 2024-07-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extcommungrievancemechanism', '0004_rename_unique_identification_of_company_acknolegement_workergrievance_unique_identification_of_compa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintandclaimrecord',
            name='claim_category',
            field=models.CharField(choices=[('Odor', 'Odor'), ('Noise', 'Noise'), ('Effluents', 'Effluents'), ('Company vehicles', 'Company vehicles'), ('Flow of migrant workers', 'Flow of migrant workers'), ('Security personnel', 'Security personnel'), ('GBV/SA/SEA', 'Gbv'), ('Other', 'Other')], max_length=50),
        ),
    ]
