# Generated by Django 3.2.25 on 2024-06-10 08:02

import core.utils.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiodeversidadeRecursosNaturais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Biodiversidade e Recursos Naturais',
                'verbose_name_plural': 'Biodiversidade e Recursos Naturais',
            },
        ),
        migrations.CreateModel(
            name='ConsultationAndEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EnvironAndSocialRiskAndImapactAssessement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('life_cycle', models.CharField(choices=[('PRE_CONSTRUCAO', 'Pré-Construção'), ('CONSTRUCAO', 'Construção'), ('OPERACAO', 'Operação'), ('DESATIVACAO', 'Desativação'), ('ENCERRAMENTO', 'Encerramento'), ('REINTEGRACAO_RESTAURACAO', 'Reintegração/Restauração')], max_length=50)),
                ('statute', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=50)),
                ('extension', models.CharField(choices=[('LOCAL', 'Local'), ('REGIONAL', 'Regional'), ('NACIONAL', 'Nacional'), ('GLOBAL', 'Global')], max_length=50)),
                ('duration', models.CharField(choices=[('CURTO_PRAZO', 'Curto Prazo'), ('MEDIO_PRAZO', 'Médio Prazo'), ('LONGO_PRAZO', 'Longo Prazo')], max_length=50)),
                ('intensity', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], max_length=50)),
                ('probability', models.CharField(choices=[('IMPROVAVEL', 'Improvável'), ('PROVAVEL', 'Provável'), ('ALTAMENTE_PROVAVEL', 'Altamente Provável'), ('DEFINITIVA', 'Definitiva')], max_length=50)),
                ('significance', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('description_of_measures', models.TextField()),
                ('deadline', models.CharField(max_length=255)),
                ('effectiveness_assessment', models.TextField()),
                ('compliance_requirements', models.TextField()),
                ('observations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalSocialScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('relevant_standard', models.CharField(blank=True, max_length=255, null=True)),
                ('recomended_actions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalRequirementControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('document_title', models.CharField(max_length=255)),
                ('effective_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('AMENDED', 'Amended')], max_length=50)),
                ('amended_description', models.TextField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('law_file', models.FileField(blank=True, null=True, upload_to=core.utils.utils.law_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreliminaryEnvironmentalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('TURISTICA', 'Turística'), ('INDUSTRIAL', 'Industrial'), ('AGRO_PECUARIA', 'Agro-Pecuária'), ('ENERGETICA', 'Energética'), ('SERVICOS', 'Serviços'), ('OUTRA', 'Outra')], max_length=255)),
                ('other_activity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('development_stage', models.CharField(choices=[('NOVA', 'Nova'), ('REABILITACAO', 'Reabilitação'), ('EXPANSAO', 'Expansão'), ('OUTRO', 'Outro')], max_length=255)),
                ('other_development_stage', models.CharField(blank=True, max_length=255, null=True)),
                ('proponents', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('activity_location', models.CharField(max_length=255)),
                ('activity_city', models.CharField(max_length=255)),
                ('activity_locality', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_district', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_province', models.CharField(choices=[('MAPUTO', 'Maputo'), ('MAPUTO_CITY', 'Maputo City'), ('GAZA', 'Gaza'), ('INHAMBANE', 'Inhambane'), ('SOFALA', 'Sofala'), ('MANICA', 'Manica'), ('TETE', 'Tete'), ('ZAMBEZIA', 'Zambezia'), ('NAMPULA', 'Nampula'), ('CABO_DELGADO', 'Cabo Delgado'), ('NIASSA', 'Niassa')], max_length=255)),
                ('geographic_coordinates', models.TextField(blank=True, null=True)),
                ('insertion_point', models.CharField(choices=[('RURAL', 'Rural'), ('URBANO', 'Urbano'), ('PERIURBANO', 'Periurbano')], max_length=255)),
                ('territorial_planning_framework', models.CharField(choices=[('ESPACO_HABITACIONAL', 'Espaço Habitacional'), ('INDUSTRIAL', 'Industrial'), ('SERVICOS', 'Serviços'), ('OUTRO', 'Outro')], max_length=255)),
                ('activity_infrastructure', models.TextField(blank=True, null=True)),
                ('associated_activities', models.TextField(blank=True, null=True)),
                ('construction_operation_technology_description', models.TextField(blank=True, null=True)),
                ('main_complementary_activities', models.TextField(blank=True, null=True)),
                ('labor_type_quantity_origin', models.TextField(blank=True, null=True)),
                ('raw_materials_type_quantity_origin_and_provenance', models.TextField(blank=True, null=True)),
                ('chemicals_used', models.TextField(blank=True, null=True)),
                ('type_origin_water_energy_consumption', models.TextField(blank=True, null=True)),
                ('fuels_lubricants_origin', models.TextField(blank=True, null=True)),
                ('other_resources_needed', models.TextField(blank=True, null=True)),
                ('land_ownership', models.TextField(blank=True, null=True)),
                ('activity_location_alternatives', models.TextField(blank=True, null=True)),
                ('brief_description_on_local_regional_ref_env_situation', models.TextField(blank=True, null=True)),
                ('physical_characteristics_of_activity_site', models.TextField(blank=True, choices=[('PLANICIE', 'Planície'), ('PLANALTO', 'Planalto'), ('VALE', 'Vale'), ('MONTANHA', 'Montanha')], null=True)),
                ('predominant_ecosystems', models.TextField(blank=True, choices=[('FLUVIAL', 'Fluvial'), ('LACUSTRE', 'Lacustre'), ('MARINHO', 'Marinho'), ('TERRESTRE', 'Terrestre')], null=True)),
                ('location_zone', models.TextField(blank=True, choices=[('COSTEIRA', 'Costeira'), ('INTERIOR', 'Interior'), ('ILHA', 'Ilha')], null=True)),
                ('type_predominant_vegetation', models.TextField(blank=True, choices=[('FLORESTA', 'Floresta'), ('SAVANA', 'Savana'), ('OUTRO', 'Outro')], null=True)),
                ('land_use', models.TextField(blank=True, choices=[('AGROPECUARIO', 'Agropecuário'), ('HABITACIONAL', 'Habitacional'), ('INDUSTRIAL', 'Industrial'), ('PROTECCAO', 'Proteção'), ('OUTRO', 'Outro')], null=True)),
                ('existing_infrastructure_around_activity_area', models.TextField(blank=True, null=True)),
                ('total_investment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RisksAndImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contract_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('contractor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('location', models.CharField(max_length=255)),
                ('geographic_coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('approximate_area', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibleForFillingForm',
            fields=[
                ('contactperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riskmanagement.contactperson')),
            ],
            bases=('riskmanagement.contactperson',),
        ),
        migrations.CreateModel(
            name='ResponsibleForVerification',
            fields=[
                ('contactperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riskmanagement.contactperson')),
            ],
            bases=('riskmanagement.contactperson',),
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_category', models.CharField(choices=[('ALTO', 'Alto Risco'), ('SUBSTANCIAL', 'Risco Substancial'), ('MODERADO', 'Risco Moderado'), ('BAIXO', 'Risco Baixo')], max_length=15)),
                ('description', models.TextField()),
                ('instruments_to_be_developed', models.TextField()),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to='riskmanagement.subproject')),
            ],
        ),
    ]
