# Generated by Django 3.2.25 on 2024-05-29 17:17

import core.utils.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LegalRequirementControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('document_title', models.CharField(max_length=255)),
                ('effective_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('AMENDED', 'Amended')], max_length=50)),
                ('amended_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('law_file', models.FileField(blank=True, null=True, upload_to=core.utils.utils.law_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='RisksAndImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Arias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('life_cycle', models.CharField(choices=[('PRE_CONSTRUCAO', 'Pré-Construção'), ('CONSTRUCAO', 'Construção'), ('OPERACAO', 'Operação'), ('DESATIVACAO', 'Desativação'), ('ENCERRAMENTO', 'Encerramento'), ('REINTEGRACAO_RESTAURACAO', 'Reintegração/Restauração')], max_length=50)),
                ('statute', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=50)),
                ('extension', models.CharField(choices=[('LOCAL', 'Local'), ('REGIONAL', 'Regional'), ('NACIONAL', 'Nacional'), ('GLOBAL', 'Global')], max_length=50)),
                ('duration', models.CharField(choices=[('CURTO_PRAZO', 'Curto Prazo'), ('MEDIO_PRAZO', 'Médio Prazo'), ('LONGO_PRAZO', 'Longo Prazo')], max_length=50)),
                ('intensity', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], max_length=50)),
                ('probability', models.CharField(choices=[('IMPROVAVEL', 'Improvável'), ('PROVAVEL', 'Provável'), ('ALTAMENTE_PROVAVEL', 'Altamente Provável'), ('DEFINITIVA', 'Definitiva')], max_length=50)),
                ('significance', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('description_of_measures', models.TextField()),
                ('deadline', models.CharField(max_length=255)),
                ('effectiveness_assessment', models.TextField()),
                ('compliance_requirements', models.TextField()),
                ('observations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.department')),
                ('environmental_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.environmentalfactor')),
                ('legal_requirements', models.ManyToManyField(related_name='legal_requirements', to='riskmanagement.LegalRequirementControl')),
            ],
        ),
    ]
