# Generated by Django 3.2.25 on 2024-06-10 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riskmanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preliminaryenvironmentalinformation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preliminar_infos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legalrequirementcontrol',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='environmentalsocialscreening',
            name='biodiversidade_recursos_naturais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.biodeversidaderecursosnaturais'),
        ),
        migrations.AddField(
            model_name='environmentalsocialscreening',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks_assessement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='environmentalsocialscreening',
            name='subproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='riskmanagement.subproject'),
        ),
        migrations.AddField(
            model_name='environandsocialriskandimapactassessement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environ_and_social_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='environandsocialriskandimapactassessement',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.department'),
        ),
        migrations.AddField(
            model_name='environandsocialriskandimapactassessement',
            name='environmental_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.environmentalfactor'),
        ),
        migrations.AddField(
            model_name='environandsocialriskandimapactassessement',
            name='legal_requirements',
            field=models.ManyToManyField(related_name='legal_requirements', to='riskmanagement.LegalRequirementControl'),
        ),
        migrations.AddField(
            model_name='environandsocialriskandimapactassessement',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='environandsocialriskandimapactassessement',
            name='risks_and_impact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.risksandimpact'),
        ),
        migrations.AddField(
            model_name='consultationandengagement',
            name='subproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='riskmanagement.subproject'),
        ),
        migrations.AddField(
            model_name='environmentalsocialscreening',
            name='responsible_for_filling_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='riskmanagement.responsibleforfillingform'),
        ),
        migrations.AddField(
            model_name='environmentalsocialscreening',
            name='responsible_for_verification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='riskmanagement.responsibleforverification'),
        ),
    ]
