# Generated by Django 3.2.25 on 2024-05-29 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskmanagement', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contract_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('contractor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('location', models.CharField(max_length=255)),
                ('geographic_coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('approximate_area', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_category', models.CharField(choices=[('ALTO', 'Alto Risco'), ('SUBSTANCIAL', 'Risco Substancial'), ('MODERADO', 'Risco Moderado'), ('BAIXO', 'Risco Baixo')], max_length=15)),
                ('description', models.TextField()),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to='riskmanagement.subproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_reference', models.CharField(max_length=255)),
                ('recommended_action', models.TextField()),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_actions', to='riskmanagement.subproject')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalSocialRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('response', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('relevant_standard', models.CharField(blank=True, max_length=255, null=True)),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='riskmanagement.subproject')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='riskmanagement.subproject')),
            ],
        ),
    ]
