# Generated by Django 3.2.25 on 2025-03-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskmanagement', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environandsocialriskandimapactassessement',
            options={'verbose_name': 'FR.AS.002_Environmental and Social Risk and Impact Assessement', 'verbose_name_plural': 'FR.AS.002_Environmental and Social Risks and Impact Assessements'},
        ),
        migrations.AlterModelOptions(
            name='environmentalsocialscreening',
            options={'verbose_name': 'FR.AS.023_Environmental and Social Screening Form', 'verbose_name_plural': 'FR.AS.023_Environmental and Social Screening Forms'},
        ),
        migrations.AlterModelOptions(
            name='legalrequirementcontrol',
            options={'verbose_name': 'FR.AS.003_Legal Requirement Control', 'verbose_name_plural': 'Legal Requirements Control'},
        ),
        migrations.AlterModelOptions(
            name='preliminaryenvironmentalinformation',
            options={'verbose_name': 'MOD.AS.02_Preliminary Environmental Information Form', 'verbose_name_plural': 'MOD.AS.02_Preliminary Environmental Information Forms'},
        ),
    ]
