# Generated by Django 5.0.13 on 2025-03-16 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmanagement', '0003_auto_20250313_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environandsocialriskandimapactassessement',
            options={'verbose_name': 'FR.AS.002 Environmental and Social Risk and Impact Assessement', 'verbose_name_plural': 'FR.AS.002 Environmental and Social Risks and Impact Assessements'},
        ),
        migrations.AlterModelOptions(
            name='legalrequirementcontrol',
            options={'verbose_name': 'FR.AS.003 Legal Requirement Control', 'verbose_name_plural': 'Legal Requirements Control'},
        ),
        migrations.RemoveField(
            model_name='environandsocialriskandimapactassessement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='environmentalsocialscreening',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='legalrequirementcontrol',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='preliminaryenvironmentalinformation',
            name='created_by',
        ),
        migrations.AddField(
            model_name='environandsocialriskandimapactassessement',
            name='subproject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='environandsocialriskandimapactassessement',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='environandsocialriskandimapactassessement',
            name='departament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.department'),
        ),
        migrations.AlterField(
            model_name='environandsocialriskandimapactassessement',
            name='responsible',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='legalrequirementcontrol',
            name='law_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
