# Generated by Django 3.2.25 on 2024-06-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmanagement', '0003_auto_20240612_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalsocialscreening',
            name='consultation_and_engagement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
