# Generated by Django 3.2.25 on 2024-05-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskmanagement', '0003_consultationengagement_contactperson_environmentalsocialrisk_proposedaction_screeningresult_subproje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('TURISTICA', 'Turística'), ('INDUSTRIAL', 'Industrial'), ('AGRO_PECUARIA', 'Agro-Pecuária'), ('ENERGETICA', 'Energética'), ('SERVICOS', 'Serviços'), ('OUTRA', 'Outra')], max_length=50)),
                ('other_activity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('development_stage', models.CharField(choices=[('NOVA', 'Nova'), ('REABILITACAO', 'Reabilitação'), ('EXPANSAO', 'Expansão'), ('OUTRO', 'Outro')], max_length=50)),
                ('other_development_stage', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('telephone', models.CharField(max_length=255)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proponents', to='riskmanagement.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=255)),
                ('province', models.CharField(choices=[('MAPUTO', 'Maputo'), ('MAPUTO_CITY', 'Maputo City'), ('GAZA', 'Gaza'), ('INHAMBANE', 'Inhambane'), ('SOFALA', 'Sofala'), ('MANICA', 'Manica'), ('TETE', 'Tete'), ('ZAMBEZIA', 'Zambezia'), ('NAMPULA', 'Nampula'), ('CABO_DELGADO', 'Cabo Delgado'), ('NIASSA', 'Niassa')], max_length=100)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('geographic_coordinates', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='riskmanagement.activity')),
            ],
        ),
        migrations.CreateModel(
            name='LandOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_status', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_ownership', to='riskmanagement.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_investment_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='riskmanagement.activity')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_characteristics', models.TextField()),
                ('predominant_ecosystems', models.TextField()),
                ('location_zone', models.TextField()),
                ('predominant_vegetation', models.TextField()),
                ('land_use', models.TextField()),
                ('existing_infrastructure', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_situation', to='riskmanagement.activity')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativeLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_choice', models.TextField()),
                ('alternative1', models.TextField()),
                ('alternative2', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_locations', to='riskmanagement.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infrastructure', models.TextField()),
                ('associated_activities', models.TextField()),
                ('construction_technology', models.TextField()),
                ('main_complementary_activities', models.TextField()),
                ('labor_type_quantity', models.TextField()),
                ('raw_materials_type_quantity', models.TextField()),
                ('chemicals_used', models.TextField(blank=True, null=True)),
                ('water_energy_consumption', models.TextField()),
                ('fuels_lubricants', models.TextField()),
                ('other_resources', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='riskmanagement.activity')),
            ],
        ),
    ]
