# Generated by Django 3.2.25 on 2024-06-18 12:25

from django.db import migrations, models
import riskmanagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmanagement', '0005_auto_20240616_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalrequirementcontrol',
            name='law_file',
            field=models.FileField(blank=True, null=True, upload_to=riskmanagement.models.law_file_path),
        ),
    ]
