# Generated by Django 3.2.25 on 2024-07-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmanagement', '0006_alter_legalrequirementcontrol_law_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedMitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=100)),
                ('issue', models.CharField(max_length=255)),
                ('potential_impact_managed', models.CharField(max_length=255)),
                ('mitigation_measure', models.CharField(max_length=255)),
                ('timing', models.CharField(max_length=255)),
                ('responsibility_for_implementation', models.CharField(max_length=255)),
                ('means_of_verification', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlanningOrConstructionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=255)),
                ('issue', models.CharField(max_length=255)),
                ('potential_impact_managed', models.CharField(max_length=255)),
                ('mitigation_measure', models.CharField(max_length=255)),
                ('timing', models.CharField(max_length=255)),
                ('responsibility_for_implementation', models.CharField(max_length=255)),
                ('means_of_verification', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Planning/ Constructions Phase',
            },
        ),
    ]
