# Generated by Django 3.2.25 on 2024-08-21 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riskmanagement', '0007_embeddedmitigation_planningorconstructionphase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environandsocialriskandimapactassessement',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to=settings.AUTH_USER_MODEL),
        ),
    ]
