# Generated by Django 4.2.19 on 2025-02-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('revision_date', models.DateField()),
                ('document_name', models.CharField(max_length=255)),
                ('document_path', models.FileField(upload_to='documents/')),
                ('document_state', models.CharField(choices=[('REVISION', 'Revisão'), ('INUSE', 'Em uso'), ('OBSOLETE', 'Obsoleto')], max_length=50)),
                ('retention_period', models.DateField()),
                ('disposal_method', models.CharField(max_length=255)),
                ('observation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
