# Generated by Django 5.0.13 on 2025-03-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanagement', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
    ]
