# Generated by Django 3.2.25 on 2024-07-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(max_length=255)),
                ('how_is_waste_contained', models.CharField(max_length=255)),
                ('how_much_waste', models.PositiveIntegerField()),
                ('reference_number', models.CharField(max_length=255)),
                ('date_of_removal', models.DateField()),
                ('transfer_company', models.CharField(max_length=255)),
                ('spetial_instructions', models.TextField()),
            ],
            options={
                'verbose_name': 'Waste Transfer Log (FR.AS.031)',
                'verbose_name_plural': 'Waste Transfer Logs (FR.AS.031)',
            },
        ),
    ]
