# Generated by Django 5.0.13 on 2025-03-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportingmonitoringandreview', '0002_alter_wastetransferlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastetransferlog',
            options={'verbose_name': 'FR.AS.031 Waste Transfer Log', 'verbose_name_plural': 'FR.AS.031 Waste Transfer'},
        ),
    ]
