# Generated by Django 4.2.19 on 2025-02-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategic_objective', models.CharField(max_length=255)),
                ('specific_objective', models.CharField(max_length=255)),
                ('actions_for_achievement', models.TextField()),
                ('responsible_person', models.CharField(max_length=100)),
                ('necessary_resources', models.TextField()),
                ('indicator', models.CharField(max_length=100)),
                ('goal', models.CharField(max_length=100)),
                ('monitoring_frequency', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('observation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('goals', models.CharField(max_length=255)),
                ('strategies_for_achievement', models.TextField()),
            ],
        ),
    ]
