# Generated by Django 3.2.25 on 2024-06-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse', '0002_auto_20240627_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatorioacidenteincidente',
            old_name='descricao_acidente',
            new_name='descricao_do_acidente',
        ),
        migrations.RenameField(
            model_name='relatorioacidenteincidente',
            old_name='tipo_incidente',
            new_name='tipo_de_incidente',
        ),
        migrations.AlterField(
            model_name='relatorioacidenteincidente',
            name='nome_comercial_empreteiro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
