# Generated by Django 3.2.25 on 2025-02-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaverificacaokitprimeirossocorros',
            name='inspecao_realizada_por',
            field=models.CharField(max_length=255),
        ),
    ]
