# Generated by Django 3.2.25 on 2025-03-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse', '0003_alter_listaverificacaokitprimeirossocorros_inspecao_realizada_por'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentflashreport',
            options={'verbose_name': 'FR.AS.028_Incident Flash Report', 'verbose_name_plural': 'FR.AS.028_Incident Flash Reports'},
        ),
    ]
