# Generated by Django 3.2.25 on 2024-07-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse', '0003_auto_20240628_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentFlashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_incident', models.DateField()),
                ('time_incident', models.TimeField()),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('location_incident', models.CharField(max_length=255)),
                ('date_reported', models.DateField()),
                ('supervisor', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Employee', 'Employee'), ('Subcontrator', 'Subcontrator')], max_length=100)),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subcontrator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('incident_description', models.TextField()),
                ('details_of_injured_person', models.TextField()),
                ('witness_statement', models.TextField(blank=True, null=True)),
                ('preliminary_findings', models.CharField(blank=True, max_length=255, null=True)),
                ('recomendations', models.TextField()),
                ('further_investigation_required', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('incident_reportable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('lenders_to_be_notified', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('author_of_report', models.CharField(max_length=10)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('approver_name', models.CharField(max_length=100)),
                ('date_approved', models.DateField()),
                ('incidents', models.ManyToManyField(to='emergencyresponse.Incidents')),
            ],
            options={
                'verbose_name': 'Incident Flash Report (FR.AS.028)',
                'verbose_name_plural': 'Incident Flash Reports (FR.AS.028)',
            },
        ),
    ]
