# Generated by Django 5.0.13 on 2025-03-16 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse', '0004_alter_incidentflashreport_options'),
        ('riskmanagement', '0004_alter_environandsocialriskandimapactassessement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorioacidenteincidente',
            name='criado_por',
        ),
        migrations.AddField(
            model_name='relatorioacidenteincidente',
            name='subprojecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.subproject'),
        ),
        migrations.AlterField(
            model_name='relatorioacidenteincidente',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskmanagement.department'),
        ),
    ]
