# Generated by Django 5.0.13 on 2025-03-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencyresponse', '0005_remove_relatorioacidenteincidente_criado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorioacidenteincidente',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='relatorioacidenteincidente',
            name='fotografia_do_melhor_angulo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='relatorioacidenteincidente',
            name='fotografia_frontal',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='relatorioacidenteincidente',
            name='fotografia_lateral_direita',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='relatorioacidenteincidente',
            name='fotografia_lateral_esquerda',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='relatorioacidenteincidente',
            name='fotografia_posterior',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
